- .github/workflows/rust.yml
Fixes: #1 
There are not many changes in comparison to the workflow in the driver's repository, however I tried to do some changes and they were either not necessary or not possible:
- If we want to `build` without warnings, it's better to add a flag (`-D warnings`) to clippy than trying to make `cargo build` fail in case of warnings.
- Creating a Scylla cluster using Github workflows seems really difficult if not impossible. The Github workflows uses Docker and we can't pass the `seeds` argument when creating a container. I described this issue in more detail on Slack. 
I did not use the `cargo check` step, because it was not mentioned in the issue and as far as I know, it only checks for errors that `cargo build` should fail on anyway.
I also removed flags connected to the `examples` …
> Set up basic workflow

- scylla-cdc/Cargo.toml
- scylla-cdc/src/consumer.rs
- scylla-cdc/src/lib.rs
Fixes: #5 
This pull request adds an interface for consuming changes from CDC table. 
The module `consumer` provides a `Consumer` trait and a `ConsumerFactory` trait that define interface used by the reader component. Data from the table is passed to a consumer in a `CDCRow` object. `CDCSchema` is used to create new `CDCRow` objects.
> Interface for consuming changes

- scylla-cdc/Cargo.toml
- scylla-cdc/src/consumer.rs
Fixes #26
I added support for async operations for Consumer trait by introducing a new dependency `async-trait` that is advised as per [source](https://smallcultfollowing.com/babysteps/blog/2019/10/26/async-fn-in-traits-are-hard/) and making Consumer trait async.
> Added support for async operations inside Consumer trait.

- scylla-cdc-replicator/src/replication_tests.rs
- scylla-cdc-replicator/src/replicator_consumer.rs
Fixes #19 
This PR adds support for updating and inserting operations with non-frozen lists.
It also includes a small refactor for query responsible for deleting a row.
> Replicator: add support for inserting and updating non-frozen list columns.

- scylla-cdc-replicator/src/replicator_consumer.rs
In #10 it turned out that Clippy version used in Github actions has been updated recently and our code no longer passes Clippy checks. This PR addresses this issue.
> Fix clippy complaints about ok_or vs ok_or_else

- scylla-cdc-replicator/src/replication_tests.rs
This PR adds comparing timestamps of all non-partition & non-clustering columns for all rows.
Edit: Since cql `writetime` function doesn't work for non-frozen collections, we skip them and compare only native types and frozen collections.
> Replicator: add compare timestamps in the tests

- scylla-cdc-replicator/src/replication_tests.rs
- scylla-cdc-replicator/src/replicator_consumer.rs
Fixes #22
The PR adds support for inserting and updating non-frozen User Defined Type (UDT) columns.
Also includes small polishing to avoid `cargo clippy` warnings.
It's currently blocked by [this](https://github.com/scylladb/scylla-rust-driver/pull/415) PR for the rust driver.
> Replicator: Add support to insert and update non-frozen UDTs

- .github/workflows/rust.yml
- scylla-cdc-replicator/src/replication_tests.rs
This PR changes GitHub workflow to make it analyze with linter the testing code.
> Make cargo clippy analyze the testing code in the GitHub workflow

- scylla-cdc-printer/src/printer.rs
As I understand there are no CDC rows with cdc$time less than generation they belong to.
So passing to StreamReader a start_timestamp much earlier than the generation given by stream_ids produces multiple unnecessary queries for rows from empty time intervals.
Am I right?
> Optimize: Attempt to narrow down time window for StreamReaders in CDCLogPrinter

- scylla-cdc/src/stream_generations.rs
I have just found out that I forgot to write a test for `fetch_generations_continuously`. Once I have started to implement it it has turned out that the aforementioned method is bugged. So this PR should clean everything up.
> Fix fetch_generations_continuously

- scylla-cdc-printer/src/printer.rs
- scylla-cdc/Cargo.toml
- scylla-cdc/src/consumer.rs
- scylla-cdc/src/e2e_tests.rs
- scylla-cdc/src/lib.rs
- scylla-cdc/src/log_reader.rs
- scylla-cdc/src/stream_reader.rs
Fixes #44 
This PR adds a base for creating e2e tests that check if operations in CDC are consumed in a proper order. 
As for now, some things are simplified:
- Only Insert and Update operations are supported.
- The table has the following schema: `(pk <PK_TYPE>, ck int, v int, primary key (pk, ck))` where `<PK_TYPE>` is the type of the partition key. Support for complex partition keys might be added later.
This is because these tests should only check the order of the operations and the only thing that may have an impact on it is the partition key. 
In addition, bugs regarding the `StreamReader` have been found and fixed thanks to these tests.
> Create base for e2e tests.

- scylla-cdc/src/log_reader.rs
If my understanding is correct new generation can prolong a lifetime of stream readers and continuous calls to `CDCLogReader.stop_at` could even prevent them from stopping.
> Enforce log reader stop after failure of one of the stream readers

- scylla-cdc-printer/src/printer.rs
- scylla-cdc/src/e2e_tests.rs
- scylla-cdc/src/log_reader.rs
Resolves #58
This PR replaces CDC log reader and CDC reader worker constructors with too many arguments by adding CDC log reader builder.
> Cdc log reader builder

- scylla-cdc/src/log_reader.rs
The default safety interval should have been 30 seconds but not 3 according to this comment: https://github.com/piodul/scylla-cdc-rust/pull/71#issuecomment-1104991068
> Fix default safety interval to be 30 sec

- scylla-cdc-printer/src/printer.rs
- scylla-cdc/Cargo.toml
- scylla-cdc/src/cdc_types.rs
- scylla-cdc/src/consumer.rs
Fixes #89
This PR adds pretty printing for CDC rows (an example is attached below).
Things to improve: 
* No information about the column schema whether it is frozen, its actual type, or its column kind (regular, primary key, or clustering key).
* The columns appear unordered. I think it would be helpful to have primary keys and clustering keys separated from the regular columns.
* As `Display` trait is not implemented for `CqlType`, I used `{:?}` format specifier to pretty print values, but maybe it would be better to match `CqlType` and print type and value separately.
> Pretty printer

- scylla-cdc/src/log_reader.rs
Previously, we mapped a StreamReader to each stream in 1-1 fashion. I have changed it to use multiple streams grouped by vnodes.
> Optimization: make each StreamReader use multiple streams

- scylla-cdc-printer/src/main.rs
- scylla-cdc-replicator/src/main.rs
Currently, in the printer and replicator, we implicitly use deprecated unit variant `clap::ArgAction::StoreValue`. This causes our workflows to fail, as we can see [here](https://github.com/piodul/scylla-cdc-rust/runs/6878180188?check_suite_focus=true#step:5:342). I have changed it to explicitly use `clap::ArgAction::Set` instead.
> Change deprecated clap functions to their alternatives.

- scylla-cdc/src/checkpoints.rs
As mentioned in the [comment](https://github.com/piodul/scylla-cdc-rust/pull/69#discussion_r897924956), the task cannot fail, it shouldn't even return, so it certainly shouldn't return `Result<()>`.
I have changed it to return `()` since Never type is still experimental in Rust.
> Change return type of the task in `start_saving_checkpoints`.

- scylla-cdc-printer/Cargo.toml
- scylla-cdc-replicator/Cargo.toml
Followup to #101 
Programs couldn't compile if someone had pre-3.2 version of the Clap crate.
> Bumped the required Clap version to 3.2.

- LICENSE.txt
- README.md
- scylla-cdc/src/cdc_types.rs
- scylla-cdc/src/checkpoints.rs
- scylla-cdc/src/consumer.rs
- scylla-cdc/src/lib.rs
- scylla-cdc/src/log_reader.rs
- scylla-cdc/src/stream_reader.rs
- tutorial.md
Fixes #75 
This PR adds a file tutorial.md which contains a short tutorial about how to use our library. It also fills missing documentation, adds the project's license and a readme.
> Create a tutorial for the library

- scylla-cdc/Cargo.toml
One of the doctests was failing, because it did not compile due to a lack of one feature of Tokio. This PR adds this feature in dev-dependencies.
> Fix failing doctest in scylla-cdc/src/lib.rs

- scylla-cdc-printer/Cargo.toml
- scylla-cdc-printer/src/printer.rs
- scylla-cdc-replicator/Cargo.toml
- scylla-cdc-replicator/src/replication_tests.rs
- scylla-cdc-replicator/src/replicator_consumer.rs
- scylla-cdc-test-utils/Cargo.toml
- scylla-cdc/Cargo.toml
- scylla-cdc/src/stream_reader.rs
Updates Scylla Rust driver version to the latest 0.8.1 in the CDC library and in printer and replicator applications.
Fixes some minor cargo clippy warnings related to the use of deprecated functions.
> Update Scylla Rust driver version to 0.8.1

- scylla-cdc-printer/src/printer.rs
Fixes bug mentioned in https://github.com/scylladb/scylla-cdc-rust/pull/116#discussion_r1187364671
> Printer: use nanos to retrive `NaiveDateTime` timestamp

- scylla-cdc-printer/Cargo.toml
- scylla-cdc-replicator/Cargo.toml
- scylla-cdc-replicator/src/replication_tests.rs
- scylla-cdc-replicator/src/replicator_consumer.rs
- scylla-cdc-test-utils/Cargo.toml
- scylla-cdc-test-utils/src/lib.rs
- scylla-cdc/Cargo.toml
- scylla-cdc/src/cdc_types.rs
- scylla-cdc/src/checkpoints.rs
- scylla-cdc/src/consumer.rs
- scylla-cdc/src/e2e_tests.rs
- scylla-cdc/src/log_reader.rs
- scylla-cdc/src/stream_generations.rs
- scylla-cdc/src/stream_reader.rs
Hi,
For my project I need to bump scylla driver to latest version (0.15.1 as of now), and since it also use scylla-cdc-rust, then I try to update it too...
Mainly just updating [deserialization mechanism](https://rust-driver.docs.scylladb.com/stable/migration-guides/0.15-deserialization.html) and replacing `query`/`execute` with `query_unpaged`, `execute_unpaged`, `query_iter` and `execute_single_page` (need reviews here, my adjustment might be incorrect)
> bump scylla to 0.15.1

- scylla-cdc-printer/src/printer.rs
- scylla-cdc-replicator/src/main.rs
- scylla-cdc-replicator/src/replication_tests.rs
- scylla-cdc-replicator/src/replicator_consumer.rs
- scylla-cdc-test-utils/src/lib.rs
- scylla-cdc/src/cdc_types.rs
- scylla-cdc/src/checkpoints.rs
- scylla-cdc/src/consumer.rs
- scylla-cdc/src/e2e_tests.rs
- scylla-cdc/src/stream_generations.rs
- scylla-cdc/src/stream_reader.rs
If we lose the connection to the DB while fetching the next generation, stdout is spammed with warnings and the process stops responding to ctrl-c signals. By adding a sleep with the same interval as in the case of expected fail while fetching we alleviate both of these problems.
Fixes: VECTOR-161
> add sleep after failure to fetch_generations_continuously

- scylla-cdc-printer/Cargo.toml
- scylla-cdc-replicator/Cargo.toml
- scylla-cdc-test-utils/Cargo.toml
- scylla-cdc/Cargo.toml
- scylla-cdc/src/consumer.rs
1. A bug (_deathloop_) has been fixed (#133).
2. Rust Driver version is bumped to 1.3.1.
> Release 0.4.1
