scylladb/scylla-cdc-rust

.github/workflows/rust.yml
.gitignore
scylla-cdc/Cargo.toml
scylla-cdc/src/lib.rs
scylla-cdc/src/stream_generations.rs

Fixes: #2 
I have deleted init commit by accident while squashing my commits. This resulted in the closing of the previous PR. I couldn't reopen it, so I am opening another one. >_<
Applied changes suggested by #6

Generation Fetcher implementation.

---

scylla-cdc/Cargo.toml
scylla-cdc/src/stream_generations.rs

Convert boxed errors into anyhow errors

---

.gitignore
scylla-cdc/src/cdc_types.rs
scylla-cdc/src/consumer.rs
scylla-cdc/src/lib.rs
scylla-cdc/src/reader.rs
scylla-cdc/src/stream_generations.rs

Added Stream Reader Component

---

scylla-cdc/src/consumer.rs

As in issue description:
>Currently, `CDCRow` allows only for borrowing values from it (e.g. `pub fn get_value(&self, name: &str) -> &Option<CqlValue>)`, but does not allow to move those values out. Sometimes, users might need to operate on CqlValues directly instead of references, and cloning the value (...which is not yet implemented in the driver...) might be expensive for collections.
Now users can take values from `CDCRow` leaving `None` in place of the value taken.

Added possibility to move values out of CDCRow

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs
scylla-cdc/src/consumer.rs

Add error propagation from consume_cdc

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs

I have added support for INSERT/UPDATE/DELETE queries involving non-frozen set type.

Replicator: add support for non-frozen sets

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs

Replicator: add support for partition delete

---

Cargo.toml
scylla-cdc-printer/Cargo.toml
scylla-cdc-printer/src/lib.rs
scylla-cdc-printer/src/printer.rs
scylla-cdc/src/cdc_types.rs
scylla-cdc/src/lib.rs
scylla-cdc/src/stream_generations.rs

Resolves #4 
This is WIP.
I have two questions:
Should Readers for distinct streams work in separate tokio tasks?
Since the only thing this library does is printing to stdout and it's probably not gonna do it anymore in the final version, do we require tests for it at this point? I mean, I could capture stdout somehow, there are surely some ways to achieve it in Rust but is it worth the effort? I've assumed not, so no tests from me this time.

Implement simple CDC Log printer

---

scylla-cdc-printer/src/printer.rs

During @procrastinationfighter's work on #12 in #54 some serious problems with CDCLogPrinter were revealed.
This PR attempts to fix them.

Fix CDCLogPrinter

---

scylla-cdc-replicator/src/replicator_consumer.rs

This is some quick and probably dirty (as it introduces some new cloning) fix.
Closes #65

Fix clippy complaints about vectors instead of slices.

---

scylla-cdc-replicator/src/replication_tests.rs

Inline CQL values into query string in replication tests

---

scylla-cdc-replicator/src/replicator_consumer.rs

Fixes #33
This PR includes a small design refactoring in `ReplicatorConsumer`, in order to not pass the whole `self` object to the functions, instead only the necessary fields of `ReplicationConsumer` will be passed. This will allow us to easily add a new mutable field to the `ReplicatorConsumer` struct and update it in the functions.
The dynamic queries are lazily precomputed and stored in a map, however, a dynamic query to delete UDT elements is strictly dependent on the set of indices of UDT fields to be deleted. So, that part is left unmodified.

Replicator: Precompute dynamic queries

---

.github/workflows/rust.yml
scylla-cdc-printer/src/printer.rs
scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc/src/consumer.rs
scylla-cdc/src/lib.rs
scylla-cdc/src/stream_generations.rs
scylla-cdc/src/stream_reader.rs
scylla-cdc/src/test_utilities.rs

Parallelize tests

---

scylla-cdc-replicator/src/replication_tests.rs

Check if replication went correctly after each query

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs
scylla-cdc/src/consumer.rs

The scope of this PR is much smaller than promised due to unexpected technical difficulties. I will try to resolve them later.
Closes #25

Implement range row deletes

---

scylla-cdc-printer/src/printer.rs
scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc/src/consumer.rs
scylla-cdc/src/stream_generations.rs
scylla-cdc/src/stream_reader.rs
scylla-cdc/src/test_utilities.rs

Move test database setup to separate module

---

scylla-cdc-replicator/Cargo.toml
scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs
scylla-cdc/Cargo.toml

UUID version in driver was changed and it causes some problems here.

Adjust uuid version to the one used in scylla-rust-driver

---

scylla-cdc-replicator/src/replicator_consumer.rs

Replicator: Cache queries through common interface

---

scylla-cdc/src/e2e_tests.rs

As in the title.
[https://github.com/piodul/scylla-cdc-rust/pull/46/files#r859401423](url).
Also: refactor the tests to use uniquely named keyspaces and other tools from tests_utilites while we're at it.

Fix e2e_tests error resulting in not comparing expected and actual operations lengths after a difference was found in previous loop iterations

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs

#74 Fix UDT replication fail

---

scylla-cdc/src/log_reader.rs

Change CDCLogReader constructor visibility

---

scylla-cdc-printer/Cargo.toml
scylla-cdc-printer/src/lib.rs
scylla-cdc-printer/src/main.rs
scylla-cdc-printer/src/printer.rs

Make printer executable

---

scylla-cdc-replicator/Cargo.toml
scylla-cdc-replicator/src/main.rs
scylla-cdc-replicator/src/replicator.rs
scylla-cdc-replicator/src/replicator_consumer.rs

As in the title - this PR attempts to make replicator executable.
We follow the interface from Java and Go versions of the library (at least when it comes to the options we support at the moment).
A few questions:
1. What are the values for `window_size`, `safety_interval` and `sleep_interval` we should use here?
2. Am I assuming correctly that the replicator starts to replicate from the beginning - timestamp 0? This will probably be changed anyway once @macher259 completes progress saving task, right?
3. The `end_timestamp` argument in CDCLogReader looks definitely awkard. IIRC @Gor027 you were working on removing it, right? How is it going?
4. Should we handle SIGINTs gracefully? Is there something to be done here or the SIGINT drops the handle by itself?

Make replicator executable

---

scylla-cdc/src/log_reader.rs

Fixes #72
This PR adds additional checking for a potentially missed generation. As `next_generation`'s value is set to `None` during the execution and that logic is used in other places, I decided to not use `next_generation` as an argument to try to fetch the next generation, instead, a new variable `last_fetched_generation` is introduced to keep track of the last generation.

Check for potentially missed generation

---

scylla-cdc/src/stream_reader.rs

Manual tests show that this way partition keys are indeed calculated.

Unpack stream_id_vec bindings in order to allow driver to calculate correct partition key

---

scylla-cdc/src/stream_reader.rs

Avoid caching cdc row fetching queries in stream reader

---

scylla-cdc-printer/Cargo.toml
scylla-cdc-replicator/Cargo.toml
scylla-cdc-test-utils/Cargo.toml
scylla-cdc/Cargo.toml

Change required Scylla Rust Driver version to a fixed one.

---

scylla-cdc/src/stream_reader.rs

Fixes #107 
This pull request changes the way the `StreamReader` reads the CDC log. Now, it uses `execute_paged` and sleeps in case of a timeout. The process panics in case of other database error than a timeout.

Handle timeouts in StreamReader

---

scylla-cdc/src/log_reader.rs

Fixes #100
In these tests, there are three scenarios:
- every consumer fails
- every third consumer fails
- every second consumer panics
Also, see my comment about the source of the bug that provoked this issue: https://github.com/piodul/scylla-cdc-rust/issues/100#issuecomment-1179729824

Log reader: Add tests for handling errors

---

.gitignore
Cargo.toml
scylla-cdc-printer/Cargo.toml
scylla-cdc-printer/src/printer.rs
scylla-cdc-replicator/Cargo.toml
scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs
scylla-cdc-test-utils/Cargo.toml
scylla-cdc/Cargo.toml
scylla-cdc/src/cdc_types.rs
scylla-cdc/src/checkpoints.rs
scylla-cdc/src/consumer.rs
scylla-cdc/src/e2e_tests.rs
scylla-cdc/src/stream_generations.rs
scylla-cdc/src/stream_reader.rs

I was hacking around Rust Driver again and had the need to use the CDC project for a new PoC. After digging into a few forks I found a couple ones with pieces for bring back this project to life (cheers @abastian and @tqwewe). 
All tests seems to be running properly with the rust driver 0.13.1 but probably the changes needs to be validated by you folks, so here it goes.
PS: I literally just bumped the branch from @abastian :p

feat: scylla driver 0.13.1

---

scylla-cdc-replicator/src/replication_tests.rs
scylla-cdc-replicator/src/replicator_consumer.rs

Change repeat().take() to repeat_n() iterator.

fix: address clippy failure
